[package]
name = "mckernant1-tools"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "My random tools"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
